name: CICD

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Go Setup
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: |
          go version
          go get -d golang.org/x/lint/golint
      - name: Run build
        run: go build cmd/
      - name: Run vet and lint
        run: |
          go vet ./...
          go lint ./...
      - name: Run go build
        run: |
          go test -v ./...
